from django.db import models

# Create your models here.
class SchoolFastFacts(models.Model):
	year = models.CharField('School Year', max_length=10)
	name = models.CharField('School Name', max_length=120)
	school_id = models.IntegerField('School ID', primary_key=True)
	district_name = models.ForeignKey('DistrictFastFacts', blank = True, null = True, on_delete = models.CASCADE)
	aun = models.IntegerField('AUN')
	street_address = models.CharField('Street Address', max_length=120)
	city_address = models.CharField('City Address', max_length=50)
	state_address = models.CharField('State Address', max_length=10)
	zip_code = models.CharField('Zip Code', max_length=10)
	website = models.URLField('Website Address')
	phone_number = models.CharField('Phone Number', max_length=25)
	grades_offered = models.CharField('Grades Offered', max_length=50)
	title_1_school = models.CharField('Title 1 School', max_length=20)
	enrollment = models.IntegerField('Enrollment')
	gifted_students = models.DecimalField('Gifted Students', max_digits=4, decimal_places=2)
	intermediate_unit_name = models.CharField('Intermediate Unit Name', max_length=120)
	intermediate_unit_website = models.URLField('Intermediate Unit Website Address')
	american_indian_or_alaskan_native = models.DecimalField('American Indian or Alaskan Native', max_digits=4, decimal_places=2)
	asian = models.DecimalField('Asian', max_digits=4, decimal_places=2)
	pacific_islander = models.DecimalField('Pacific Islander', max_digits=4, decimal_places=2)
	african_american = models.DecimalField('Black/African American', max_digits=4, decimal_places=2)
	hispanic = models.DecimalField('Hispanic', max_digits=4, decimal_places=2)
	white = models.DecimalField('White', max_digits=4, decimal_places=2)
	two_or_more_races = models.DecimalField('Two or More Races', max_digits=4, decimal_places=2)
	economically_disadvantaged = models.DecimalField('Economically Disadvantaged', max_digits=4, decimal_places=2)
	english_learner = models.DecimalField('English Learner', max_digits=4, decimal_places=2)
	special_education = models.DecimalField('Special Education', max_digits=4, decimal_places=2)
	female = models.DecimalField('Female', max_digits=4, decimal_places=2)
	male = models.DecimalField('Male', max_digits=4, decimal_places=2)
	career_and_technical_programs = models.CharField('Career and Technical Programs', max_length=120, blank=True)

	def __str__(self):
		return self.name

class DistrictFastFacts(models.Model):
	year = models.CharField('District Year', max_length=10)
	name = models.CharField('District Name', max_length=120)
	aun = models.IntegerField('AUN')
	two_or_more_races = models.DecimalField('Two or More Races', max_digits=4, decimal_places=2)
	american_indian_or_alaskan_native = models.DecimalField('American Indian or Alaskan Native', max_digits=4, decimal_places=2)
	asian = models.DecimalField('Asian', max_digits=4, decimal_places=2)
	african_american = models.DecimalField('Black/African American', max_digits=4, decimal_places=2)
	career_and_technical_center_name = models.CharField('Career and Technical Center Name', max_length=120)
	career_and_technical_center_website = models.URLField('Career and Technical Center Website Address', blank=True)
	charter_school_enrollment = models.IntegerField('Charter School Enrollment')
	city_address = models.CharField('City Address', max_length=50)
	state_address = models.CharField('State Address', max_length=10)
	street_address = models.CharField('Street Address', max_length=120)
	enrollment = models.IntegerField('Enrollment')
	zip_code = models.CharField('Zip Code', max_length=10)
	economically_disadvantaged = models.DecimalField('Economically Disadvantaged', max_digits=4, decimal_places=2)
	english_learner = models.DecimalField('English Learner', max_digits=4, decimal_places=2)
	enrollment_in_partnering_career_technical_centers = models.IntegerField('Enrollment in Partnering Career/Technical Centers')
	female = models.DecimalField('Female', max_digits=4, decimal_places=2)
	foster_care = models.DecimalField('Foster Care', max_digits=4, decimal_places=2)
	geographic_size = models.DecimalField('Geographic Size (miles)', max_digits=8, decimal_places=2)
	grades_offered = models.CharField('Grades Offered', max_length=50)
	hispanic = models.DecimalField('Hispanic', max_digits=4, decimal_places=2)
	homeless = models.DecimalField('Homeless', max_digits=4, decimal_places=2)
	intermediate_unit_name = models.CharField('Intermediate Unit Name', max_length=120)
	intermediate_unit_website = intermediate_unit_website = models.URLField('Intermediate Unit Website Address')
	male = models.DecimalField('Male', max_digits=4, decimal_places=2)
	miliitary_connected = models.DecimalField('Military Connected', max_digits=4, decimal_places=2)
	pacific_islander = models.DecimalField('Pacific Islander', max_digits=4, decimal_places=2)
	num_of_schools = models.IntegerField('Number of Schools')
	gifted_students = models.DecimalField('Gifted Students', max_digits=4, decimal_places=2)
	special_education = models.DecimalField('Special Education', max_digits=4, decimal_places=2)
	phone_number = models.CharField('Phone Number', max_length=25)
	website = models.URLField('Website Address')
	white = models.DecimalField('White', max_digits=4, decimal_places=2)
	schools_in_district = models.ManyToManyField('SchoolFastFacts', blank=True)

	def __str__(self):
		return self.name