# Generated by Django 5.1.1 on 2024-09-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFastFacts',
            fields=[
                ('year', models.CharField(max_length=10, verbose_name='School Year')),
                ('name', models.CharField(max_length=120, verbose_name='School Name')),
                ('school_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='School ID')),
                ('district_name', models.CharField(max_length=120, verbose_name='District Name')),
                ('aun', models.IntegerField(verbose_name='AUN')),
                ('street_address', models.CharField(max_length=120, verbose_name='Street Address')),
                ('city_address', models.CharField(max_length=50, verbose_name='City Address')),
                ('state_address', models.CharField(max_length=10, verbose_name='State Address')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('website', models.URLField(verbose_name='Website Address')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('grades_offered', models.CharField(max_length=50, verbose_name='Grades Offered')),
                ('title_1_school', models.CharField(max_length=20, verbose_name='Title 1 School')),
                ('enrollment', models.IntegerField(verbose_name='Enrollment')),
                ('gifted_students', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Gifted Students')),
                ('intermediate_unit_name', models.CharField(max_length=120, verbose_name='Intermediate Unit Name')),
                ('intermediate_unit_website', models.URLField(verbose_name='Intermediate Unit Website Address')),
                ('american_indian_or_alaskan_native', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='American Indian or Alaskan Native')),
                ('asian', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Asian')),
                ('pacific_islander', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Pacific Islander')),
                ('african_american', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Black/African American')),
                ('hispanic', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Hispanic')),
                ('white', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='White')),
                ('two_or_more_races', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Two or More Races')),
                ('economically_disadvantaged', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Economically Disadvantaged')),
                ('english_learner', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='English Learner')),
                ('special_education', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Special Education')),
                ('female', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Female')),
                ('male', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Male')),
                ('career_and_technical_programs', models.CharField(max_length=40, verbose_name='Career and Technical Programs')),
            ],
        ),
    ]
