# Generated by Django 5.1.1 on 2024-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictFastFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='District Year')),
                ('name', models.CharField(max_length=120, verbose_name='District Name')),
                ('aun', models.IntegerField(verbose_name='AUN')),
                ('two_or_more_races', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Two or More Races')),
                ('american_indian_or_alaskan_native', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='American Indian or Alaskan Native')),
                ('asian', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Asian')),
                ('african_american', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Black/African American')),
                ('career_and_technical_center_name', models.CharField(max_length=120, verbose_name='Career and Technical Center Name')),
                ('career_and_technical_center_website', models.URLField(verbose_name='Career and Technical Center Website Address')),
                ('charter_school_enrollment', models.IntegerField(verbose_name='Charter School Enrollment')),
                ('city_address', models.CharField(max_length=50, verbose_name='City Address')),
                ('state_address', models.CharField(max_length=10, verbose_name='State Address')),
                ('street_address', models.CharField(max_length=120, verbose_name='Street Address')),
                ('enrollment', models.IntegerField(verbose_name='Enrollment')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('economically_disadvantaged', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Economically Disadvantaged')),
                ('english_learner', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='English Learner')),
                ('enrollment_in_partnering_career_technical_centers', models.IntegerField(verbose_name='Enrollment in Partnering Career/Technical Centers')),
                ('female', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Female')),
                ('foster_care', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Female')),
                ('geographic_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Geographic Size (miles)')),
                ('grades_offered', models.CharField(max_length=50, verbose_name='Grades Offered')),
                ('hispanic', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hispanic')),
                ('homeless', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Homeless')),
                ('intermediate_unit_name', models.CharField(max_length=120, verbose_name='Intermediate Unit Name')),
                ('intermediate_unit_website', models.URLField(verbose_name='Intermediate Unit Website Address')),
                ('male', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Male')),
                ('miliitary_connected', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Military Connected')),
                ('pacific_islander', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pacific Islander')),
                ('num_of_schools', models.IntegerField(verbose_name='Number of Schools')),
                ('gifted_students', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Gifted Students')),
                ('special_education', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Special Education')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('website', models.URLField(verbose_name='Website Address')),
                ('white', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='White')),
            ],
        ),
    ]
