# Generated by Django 5.1.1 on 2024-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0002_rename_school_extrademoschool_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderschool',
            name='female',
            field=models.FloatField(verbose_name='Female'),
        ),
        migrations.AlterField(
            model_name='genderschool',
            name='male',
            field=models.FloatField(verbose_name='Male'),
        ),
        migrations.AlterField(
            model_name='genderschool',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
    ]
