# Generated by Django 5.1.1 on 2024-09-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0002_districtfastfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtfastfacts',
            name='schools_in_district',
            field=models.ManyToManyField(blank=True, to='proj_display.schoolfastfacts'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='district_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.districtfastfacts'),
        ),
    ]
