# Generated by Django 5.1.1 on 2024-12-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0002_rename_school_extrademoschool_school_id_and_more'),
    ]

    operations = [
    ]
