# Generated by Django 5.1.1 on 2024-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0003_alter_genderschool_female_alter_genderschool_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_african_american',
            field=models.FloatField(verbose_name='African American/Black %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_am_indian_or_alaskan_native',
            field=models.FloatField(verbose_name='American Indian or Alaskan Native %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_asian',
            field=models.FloatField(verbose_name='Asian %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_hispanic',
            field=models.FloatField(verbose_name='Hispanic %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_pacific_islander',
            field=models.FloatField(verbose_name='Pacific Islander %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_two_or_more_races',
            field=models.FloatField(verbose_name='2 or More Races %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='per_white',
            field=models.FloatField(verbose_name='White %'),
        ),
        migrations.AlterField(
            model_name='districtdemographic',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_economically_disadvantaged',
            field=models.FloatField(verbose_name='Economically Disadvantaged %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_english_learner',
            field=models.FloatField(verbose_name='English Learner %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_foster_care',
            field=models.FloatField(verbose_name='Foster Care %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_gifted_student',
            field=models.FloatField(verbose_name='Gifted Student %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_homeless',
            field=models.FloatField(verbose_name='Homeless %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_military_connected',
            field=models.FloatField(verbose_name='Military Connected %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='per_special_education',
            field=models.FloatField(verbose_name='Special Education %'),
        ),
        migrations.AlterField(
            model_name='extrademodistrict',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_economically_disadvantaged',
            field=models.FloatField(verbose_name='Economically Disadvantaged %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_english_learner',
            field=models.FloatField(verbose_name='English Learner %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_foster_care',
            field=models.FloatField(verbose_name='Foster Care %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_gifted_student',
            field=models.FloatField(verbose_name='Gifted Student %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_homeless',
            field=models.FloatField(verbose_name='Homeless %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_military_connected',
            field=models.FloatField(verbose_name='Military Connected %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='per_special_education',
            field=models.FloatField(verbose_name='Special Education %'),
        ),
        migrations.AlterField(
            model_name='extrademoschool',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='genderdistrict',
            name='female',
            field=models.FloatField(verbose_name='Female %'),
        ),
        migrations.AlterField(
            model_name='genderdistrict',
            name='male',
            field=models.FloatField(verbose_name='Male %'),
        ),
        migrations.AlterField(
            model_name='genderdistrict',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_african_american',
            field=models.FloatField(verbose_name='African American/Black %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_am_indian_or_alaskan_native',
            field=models.FloatField(verbose_name='American Indian or Alaskan Native %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_asian',
            field=models.FloatField(verbose_name='Asian %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_hispanic',
            field=models.FloatField(verbose_name='Hispanic %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_pacific_islander',
            field=models.FloatField(verbose_name='Pacific Islander %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_two_or_more_races',
            field=models.FloatField(verbose_name='2 or More Races %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='per_white',
            field=models.FloatField(verbose_name='White %'),
        ),
        migrations.AlterField(
            model_name='schooldemographic',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='federal_non_personnel',
            field=models.FloatField(verbose_name='Federal Non-Personnel'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='federal_personnel',
            field=models.FloatField(verbose_name='Federal Personnel'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='local_non_personnel',
            field=models.FloatField(verbose_name='Local Non-Personnel'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='local_personnel',
            field=models.FloatField(verbose_name='Local Personnel'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='school_year',
            field=models.IntegerField(verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='state_non_personnel',
            field=models.FloatField(verbose_name='State Non-Personnel'),
        ),
        migrations.AlterField(
            model_name='schoolfiscaldata',
            name='state_personnel',
            field=models.FloatField(verbose_name='State Personnel'),
        ),
    ]
