# Generated by Django 5.1.1 on 2024-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0003_districtfastfacts_schools_in_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtfastfacts',
            name='foster_care',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Foster Care'),
        ),
    ]
