# Generated by Django 5.1.1 on 2024-12-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0003_auto_20241210_0148'),
    ]

    operations = [
    ]
