# Generated by Django 5.1.1 on 2024-09-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0004_alter_districtfastfacts_foster_care'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtfastfacts',
            name='asian',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Asian'),
        ),
        migrations.AlterField(
            model_name='districtfastfacts',
            name='career_and_technical_center_website',
            field=models.URLField(blank=True, verbose_name='Career and Technical Center Website Address'),
        ),
    ]
