# Generated by Django 5.1.1 on 2024-12-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0004_alter_districtdemographic_per_african_american_and_more'),
        ('proj_display', '0004_auto_20241210_0217'),
    ]

    operations = [
    ]
