# Generated by Django 5.1.1 on 2024-09-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0005_alter_districtfastfacts_asian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='african_american',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Black/African American'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='american_indian_or_alaskan_native',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='American Indian or Alaskan Native'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='asian',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Asian'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='career_and_technical_programs',
            field=models.CharField(blank=True, max_length=40, verbose_name='Career and Technical Programs'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='economically_disadvantaged',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Economically Disadvantaged'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='english_learner',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='English Learner'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='female',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Female'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='gifted_students',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Gifted Students'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='hispanic',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hispanic'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='male',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Male'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='pacific_islander',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='special_education',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Special Education'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='two_or_more_races',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Two or More Races'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='white',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='White'),
        ),
    ]
