# Generated by Django 5.1.1 on 2024-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0005_merge_20241211_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowincomepercentpubschool',
            name='percent_enrollment_from_low_income_families',
            field=models.CharField(max_length=20),
        ),
    ]
