# Generated by Django 5.1.1 on 2024-12-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0006_alter_lowincomepercentpubschool_percent_enrollment_from_low_income_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowincomepercentprivateschool',
            name='low_income_percentage',
            field=models.CharField(max_length=20),
        ),
    ]
