# Generated by Django 5.1.1 on 2024-10-01 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0006_alter_schoolfastfacts_african_american_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False, verbose_name='County ID')),
                ('county_name', models.CharField(max_length=120, verbose_name='County Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='districtfastfacts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolfastfacts',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='schoolfastfacts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolfastfacts',
            name='school_id',
        ),
        migrations.AddField(
            model_name='schoolfastfacts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtfastfacts',
            name='geographic_size',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Geographic Size (miles)'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='career_and_technical_programs',
            field=models.CharField(blank=True, max_length=120, verbose_name='Career and Technical Programs'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_aun', models.IntegerField(primary_key=True, serialize=False, verbose_name='AUN')),
                ('district_name', models.CharField(max_length=120, verbose_name='District Name')),
                ('county_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.county')),
            ],
        ),
        migrations.AlterField(
            model_name='districtfastfacts',
            name='aun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.district'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=120, verbose_name='School Name')),
                ('school_aun', models.IntegerField(primary_key=True, serialize=False, verbose_name='AUN')),
                ('district_aun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.district')),
            ],
        ),
        migrations.AlterField(
            model_name='districtfastfacts',
            name='schools_in_district',
            field=models.ManyToManyField(blank=True, to='proj_display.school'),
        ),
        migrations.AlterField(
            model_name='schoolfastfacts',
            name='aun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.school'),
        ),
    ]
