# Generated by Django 5.1.1 on 2024-10-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0007_county_remove_districtfastfacts_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtfastfacts',
            name='schools_in_district',
        ),
        migrations.AddField(
            model_name='district',
            name='schools_in_district',
            field=models.ManyToManyField(blank=True, to='proj_display.school'),
        ),
    ]
