# Generated by Django 5.1.1 on 2024-12-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0005_merge_20241211_1134'),
        ('proj_display', '0007_alter_lowincomepercentprivateschool_low_income_percentage'),
    ]

    operations = [
    ]
