# Generated by Django 5.1.1 on 2024-10-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0008_remove_districtfastfacts_schools_in_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_aun',
            new_name='school_id',
        ),
    ]
