# Generated by Django 5.1.1 on 2024-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0009_rename_school_aun_school_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='School ID'),
        ),
    ]
