# Generated by Django 5.1.1 on 2024-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0010_alter_school_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='County ID'),
        ),
    ]
