# Generated by Django 5.1.1 on 2024-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0011_alter_county_county_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='schools_in_county',
            field=models.ManyToManyField(blank=True, to='proj_display.district'),
        ),
    ]
