# Generated by Django 5.1.1 on 2024-10-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0012_county_schools_in_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='schools_in_county',
            new_name='districts_in_county',
        ),
    ]
