# Generated by Django 5.1.1 on 2024-10-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0014_remove_county_districts_in_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfastfacts',
            old_name='aun',
            new_name='school_id',
        ),
    ]
