# Generated by Django 5.1.1 on 2024-10-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0015_rename_aun_schoolfastfacts_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asian', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Asian')),
                ('pacific_islander', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pacific Islander')),
                ('african_american', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Black/African American')),
                ('hispanic', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hispanic')),
                ('white', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='White')),
                ('two_or_more_races', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Two or More Races')),
                ('economically_disadvantaged', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Economically Disadvantaged')),
                ('english_learner', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='English Learner')),
                ('special_education', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Special Education')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_display.school')),
            ],
        ),
    ]
