# Generated by Django 5.1.1 on 2024-10-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_display', '0016_demographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='year',
            field=models.CharField(default=0, max_length=4, verbose_name='School Year'),
            preserve_default=False,
        ),
    ]
